// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: message.proto

package com.wx.wxfx.entity;

public interface AuthenticateOrBuilder extends
    // @@protoc_insertion_point(interface_extends:cmpark.message.Authenticate)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   *接入序列号(32个字符)
   * </pre>
   *
   * <code>string serial = 1;</code>
   * @return The serial.
   */
  String getSerial();
  /**
   * <pre>
   *接入序列号(32个字符)
   * </pre>
   *
   * <code>string serial = 1;</code>
   * @return The bytes for serial.
   */
  com.google.protobuf.ByteString
      getSerialBytes();

  /**
   * <pre>
   *接入安全码(32个字符)
   * </pre>
   *
   * <code>string secret = 2;</code>
   * @return The secret.
   */
  String getSecret();
  /**
   * <pre>
   *接入安全码(32个字符)
   * </pre>
   *
   * <code>string secret = 2;</code>
   * @return The bytes for secret.
   */
  com.google.protobuf.ByteString
      getSecretBytes();
}
