// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: message.proto

package com.wx.wxfx.entity;

/**
 * <pre>
 **
 * 场端认证消息。
 * TLS/SSL链接建立成功后, 服务端启动认证倒计时(10秒).
 * 如果没有发送或者认证失败, 服务端会关闭本次会话
 * </pre>
 *
 * Protobuf type {@code cmpark.message.Authenticate}
 */
public final class Authenticate extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:cmpark.message.Authenticate)
    AuthenticateOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Authenticate.newBuilder() to construct.
  private Authenticate(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Authenticate() {
    serial_ = "";
    secret_ = "";
  }

  @Override
  @SuppressWarnings({"unused"})
  protected Object newInstance(
      UnusedPrivateParameter unused) {
    return new Authenticate();
  }

  @Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private Authenticate(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            String s = input.readStringRequireUtf8();

            serial_ = s;
            break;
          }
          case 18: {
            String s = input.readStringRequireUtf8();

            secret_ = s;
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return Message.internal_static_cmpark_message_Authenticate_descriptor;
  }

  @Override
  protected FieldAccessorTable
      internalGetFieldAccessorTable() {
    return Message.internal_static_cmpark_message_Authenticate_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            Authenticate.class, Builder.class);
  }

  public static final int SERIAL_FIELD_NUMBER = 1;
  private volatile Object serial_;
  /**
   * <pre>
   *接入序列号(32个字符)
   * </pre>
   *
   * <code>string serial = 1;</code>
   * @return The serial.
   */
  @Override
  public String getSerial() {
    Object ref = serial_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      serial_ = s;
      return s;
    }
  }
  /**
   * <pre>
   *接入序列号(32个字符)
   * </pre>
   *
   * <code>string serial = 1;</code>
   * @return The bytes for serial.
   */
  @Override
  public com.google.protobuf.ByteString
      getSerialBytes() {
    Object ref = serial_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      serial_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int SECRET_FIELD_NUMBER = 2;
  private volatile Object secret_;
  /**
   * <pre>
   *接入安全码(32个字符)
   * </pre>
   *
   * <code>string secret = 2;</code>
   * @return The secret.
   */
  @Override
  public String getSecret() {
    Object ref = secret_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      secret_ = s;
      return s;
    }
  }
  /**
   * <pre>
   *接入安全码(32个字符)
   * </pre>
   *
   * <code>string secret = 2;</code>
   * @return The bytes for secret.
   */
  @Override
  public com.google.protobuf.ByteString
      getSecretBytes() {
    Object ref = secret_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      secret_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(serial_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, serial_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(secret_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, secret_);
    }
    unknownFields.writeTo(output);
  }

  @Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(serial_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, serial_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(secret_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, secret_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @Override
  public boolean equals(final Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof Authenticate)) {
      return super.equals(obj);
    }
    Authenticate other = (Authenticate) obj;

    if (!getSerial()
        .equals(other.getSerial())) return false;
    if (!getSecret()
        .equals(other.getSecret())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + SERIAL_FIELD_NUMBER;
    hash = (53 * hash) + getSerial().hashCode();
    hash = (37 * hash) + SECRET_FIELD_NUMBER;
    hash = (53 * hash) + getSecret().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static Authenticate parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static Authenticate parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static Authenticate parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static Authenticate parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static Authenticate parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static Authenticate parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static Authenticate parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static Authenticate parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static Authenticate parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static Authenticate parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static Authenticate parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static Authenticate parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(Authenticate prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(
      BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   **
   * 场端认证消息。
   * TLS/SSL链接建立成功后, 服务端启动认证倒计时(10秒).
   * 如果没有发送或者认证失败, 服务端会关闭本次会话
   * </pre>
   *
   * Protobuf type {@code cmpark.message.Authenticate}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:cmpark.message.Authenticate)
      AuthenticateOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Message.internal_static_cmpark_message_Authenticate_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Message.internal_static_cmpark_message_Authenticate_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Authenticate.class, Builder.class);
    }

    // Construct using com.wx.wxfx.entity.Authenticate.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @Override
    public Builder clear() {
      super.clear();
      serial_ = "";

      secret_ = "";

      return this;
    }

    @Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return Message.internal_static_cmpark_message_Authenticate_descriptor;
    }

    @Override
    public Authenticate getDefaultInstanceForType() {
      return Authenticate.getDefaultInstance();
    }

    @Override
    public Authenticate build() {
      Authenticate result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @Override
    public Authenticate buildPartial() {
      Authenticate result = new Authenticate(this);
      result.serial_ = serial_;
      result.secret_ = secret_;
      onBuilt();
      return result;
    }

    @Override
    public Builder clone() {
      return super.clone();
    }
    @Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.setField(field, value);
    }
    @Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.addRepeatedField(field, value);
    }
    @Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof Authenticate) {
        return mergeFrom((Authenticate)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(Authenticate other) {
      if (other == Authenticate.getDefaultInstance()) return this;
      if (!other.getSerial().isEmpty()) {
        serial_ = other.serial_;
        onChanged();
      }
      if (!other.getSecret().isEmpty()) {
        secret_ = other.secret_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @Override
    public final boolean isInitialized() {
      return true;
    }

    @Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Authenticate parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (Authenticate) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private Object serial_ = "";
    /**
     * <pre>
     *接入序列号(32个字符)
     * </pre>
     *
     * <code>string serial = 1;</code>
     * @return The serial.
     */
    public String getSerial() {
      Object ref = serial_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        serial_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <pre>
     *接入序列号(32个字符)
     * </pre>
     *
     * <code>string serial = 1;</code>
     * @return The bytes for serial.
     */
    public com.google.protobuf.ByteString
        getSerialBytes() {
      Object ref = serial_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        serial_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     *接入序列号(32个字符)
     * </pre>
     *
     * <code>string serial = 1;</code>
     * @param value The serial to set.
     * @return This builder for chaining.
     */
    public Builder setSerial(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      serial_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *接入序列号(32个字符)
     * </pre>
     *
     * <code>string serial = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearSerial() {
      
      serial_ = getDefaultInstance().getSerial();
      onChanged();
      return this;
    }
    /**
     * <pre>
     *接入序列号(32个字符)
     * </pre>
     *
     * <code>string serial = 1;</code>
     * @param value The bytes for serial to set.
     * @return This builder for chaining.
     */
    public Builder setSerialBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      serial_ = value;
      onChanged();
      return this;
    }

    private Object secret_ = "";
    /**
     * <pre>
     *接入安全码(32个字符)
     * </pre>
     *
     * <code>string secret = 2;</code>
     * @return The secret.
     */
    public String getSecret() {
      Object ref = secret_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        secret_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <pre>
     *接入安全码(32个字符)
     * </pre>
     *
     * <code>string secret = 2;</code>
     * @return The bytes for secret.
     */
    public com.google.protobuf.ByteString
        getSecretBytes() {
      Object ref = secret_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        secret_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     *接入安全码(32个字符)
     * </pre>
     *
     * <code>string secret = 2;</code>
     * @param value The secret to set.
     * @return This builder for chaining.
     */
    public Builder setSecret(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      secret_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *接入安全码(32个字符)
     * </pre>
     *
     * <code>string secret = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearSecret() {
      
      secret_ = getDefaultInstance().getSecret();
      onChanged();
      return this;
    }
    /**
     * <pre>
     *接入安全码(32个字符)
     * </pre>
     *
     * <code>string secret = 2;</code>
     * @param value The bytes for secret to set.
     * @return This builder for chaining.
     */
    public Builder setSecretBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      secret_ = value;
      onChanged();
      return this;
    }
    @Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:cmpark.message.Authenticate)
  }

  // @@protoc_insertion_point(class_scope:cmpark.message.Authenticate)
  private static final Authenticate DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new Authenticate();
  }

  public static Authenticate getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Authenticate>
      PARSER = new com.google.protobuf.AbstractParser<Authenticate>() {
    @Override
    public Authenticate parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new Authenticate(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<Authenticate> parser() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.Parser<Authenticate> getParserForType() {
    return PARSER;
  }

  @Override
  public Authenticate getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

