// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: message.proto

package com.wx.wxfx.entity;

public final class Message {
  private Message() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_cmpark_message_Query_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_cmpark_message_Query_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_cmpark_message_Transmission_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_cmpark_message_Transmission_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_cmpark_message_Respond_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_cmpark_message_Respond_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_cmpark_message_Authenticate_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_cmpark_message_Authenticate_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_cmpark_message_Queue_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_cmpark_message_Queue_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_cmpark_message_Space_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_cmpark_message_Space_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\rmessage.proto\022\016cmpark.message\"(\n\005Query" +
      "\022\016\n\006serial\030\001 \001(\t\022\017\n\007message\030\002 \001(\014\"\276\001\n\014Tr" +
      "ansmission\022\n\n\002ID\030\001 \001(\007\0226\n\004type\030\002 \001(\0162(.c" +
      "mpark.message.Transmission.MessageType\022\017" +
      "\n\007message\030\003 \001(\014\"Y\n\013MessageType\022\021\n\rTYPE_N" +
      "OT_USED\020\000\022\020\n\014TYPE_RESPOND\020\001\022\025\n\021TYPE_AUTH" +
      "ENTICATE\020\002\022\016\n\nTYPE_SPACE\020\003\"\345\001\n\007Respond\0221" +
      "\n\004code\030\001 \001(\0162#.cmpark.message.Respond.Re" +
      "spondCode\022\017\n\007message\030\002 \001(\014\"\225\001\n\013RespondCo" +
      "de\022\021\n\rCODE_NOT_USED\020\000\022\020\n\014CODE_SUCCESS\020\001\022" +
      "\020\n\014CODE_FAILURE\020\002\022\022\n\016CODE_DUPLICATE\020\003\022\021\n" +
      "\rCODE_MISMATCH\020\004\022\026\n\022CODE_NOT_SUPPORTED\020\005" +
      "\022\020\n\014CODE_OFFLINE\020\006\".\n\014Authenticate\022\016\n\006se" +
      "rial\030\001 \001(\t\022\016\n\006secret\030\002 \001(\t\"\025\n\005Queue\022\014\n\004s" +
      "ize\030\001 \001(\007\"(\n\005Space\022\r\n\005total\030\001 \001(\007\022\020\n\010rem" +
      "ained\030\002 \001(\007B\026\n\022com.wx.wxfx.entityP\001b\006pro" +
      "to3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_cmpark_message_Query_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_cmpark_message_Query_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_cmpark_message_Query_descriptor,
        new String[] { "Serial", "Message", });
    internal_static_cmpark_message_Transmission_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_cmpark_message_Transmission_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_cmpark_message_Transmission_descriptor,
        new String[] { "ID", "Type", "Message", });
    internal_static_cmpark_message_Respond_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_cmpark_message_Respond_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_cmpark_message_Respond_descriptor,
        new String[] { "Code", "Message", });
    internal_static_cmpark_message_Authenticate_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_cmpark_message_Authenticate_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_cmpark_message_Authenticate_descriptor,
        new String[] { "Serial", "Secret", });
    internal_static_cmpark_message_Queue_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_cmpark_message_Queue_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_cmpark_message_Queue_descriptor,
        new String[] { "Size", });
    internal_static_cmpark_message_Space_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_cmpark_message_Space_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_cmpark_message_Space_descriptor,
        new String[] { "Total", "Remained", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
