// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: message.proto

package com.wx.wxfx.entity;

public interface QueueOrBuilder extends
    // @@protoc_insertion_point(interface_extends:cmpark.message.Queue)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>fixed32 size = 1;</code>
   * @return The size.
   */
  int getSize();
}
