// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: message.proto

package com.wx.wxfx.entity;

public interface RespondOrBuilder extends
    // @@protoc_insertion_point(interface_extends:cmpark.message.Respond)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   *响应码
   * </pre>
   *
   * <code>.cmpark.message.Respond.RespondCode code = 1;</code>
   * @return The enum numeric value on the wire for code.
   */
  int getCodeValue();
  /**
   * <pre>
   *响应码
   * </pre>
   *
   * <code>.cmpark.message.Respond.RespondCode code = 1;</code>
   * @return The code.
   */
  Respond.RespondCode getCode();

  /**
   * <pre>
   *响应消息
   * </pre>
   *
   * <code>bytes message = 2;</code>
   * @return The message.
   */
  com.google.protobuf.ByteString getMessage();
}
