// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: message.proto

package com.wx.wxfx.entity;

public interface SpaceOrBuilder extends
    // @@protoc_insertion_point(interface_extends:cmpark.message.Space)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   *总车位
   * </pre>
   *
   * <code>fixed32 total = 1;</code>
   * @return The total.
   */
  int getTotal();

  /**
   * <pre>
   *剩余车位
   * </pre>
   *
   * <code>fixed32 remained = 2;</code>
   * @return The remained.
   */
  int getRemained();
}
