// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: message.proto

package com.wx.wxfx.entity;

public interface TransmissionOrBuilder extends
    // @@protoc_insertion_point(interface_extends:cmpark.message.Transmission)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   *消息ID, 请求/响应根据此字段对应
   * </pre>
   *
   * <code>fixed32 ID = 1;</code>
   * @return The iD.
   */
  int getID();

  /**
   * <pre>
   *消息类型
   * </pre>
   *
   * <code>.cmpark.message.Transmission.MessageType type = 2;</code>
   * @return The enum numeric value on the wire for type.
   */
  int getTypeValue();
  /**
   * <pre>
   *消息类型
   * </pre>
   *
   * <code>.cmpark.message.Transmission.MessageType type = 2;</code>
   * @return The type.
   */
  Transmission.MessageType getType();

  /**
   * <pre>
   *具体消息序列化后的字节
   * </pre>
   *
   * <code>bytes message = 3;</code>
   * @return The message.
   */
  com.google.protobuf.ByteString getMessage();
}
