spring:
  datasource:
    name: flyCP  # 数据源名
    url: jdbc:mysql://47.110.9.171:3306/yunpark?useUnicode=true&characterEncoding=utf8&useOldAliasMetadataBehavior=true&useSSL=false&allowMultiQueries=true
    username: park
    password: park123
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      minimum-idle: 5
      connection-timeout: 30000
      maximum-pool-size: 20
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 300
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
        useLocalTransactionState: true
        rewriteBatchedStatements: true
        cacheResultSetMetadata: true
        metadataCacheSize: 300
        cacheServerConfiguration: true
        maintainTimeStats: false
      pool-name: parkCP
      health-check-properties:
        connectivityCheckTimeoutMs: 1000
        expected99thPercentileMs: 10


mybatis-plus:
  configuration:
   log-impl: org.apache.ibatis.logging.stdout.StdOutImpl