spring:
  datasource:
    name: flyCP  # 数据源名
    url: jdbc:mysql://47.110.9.171:3306/yunpark?useUnicode=true&characterEncoding=utf8&useOldAliasMetadataBehavior=true&useSSL=false&allowMultiQueries=true
    username: park
    password: park123
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      minimum-idle: 5
      connection-timeout: 30000
      maximum-pool-size: 20
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 300
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
        useLocalTransactionState: true
        rewriteBatchedStatements: true
        cacheResultSetMetadata: true
        metadataCacheSize: 300
        cacheServerConfiguration: true
        maintainTimeStats: false
      pool-name: parkCP
      health-check-properties:

  redis:
    host: 119.45.63.249  # Redis ip地址8.129.174.193
    #    host: 192.168.110.172  # Redis ip地址8.129.174.193
    #    host: 172.16.16.11
    port: 6399  #Redis 端口号
    password: YUwang00
    lettuce:
      pool:
        max-active: 8 # 连接池最大连接数（使用负值表示没有限制）
        max-idle: 8 #连接池中的最大空闲连接
        max-wait: -1ms #连接池最大阻塞等待时间（使用负值表示没有限制）
        min-idle: 0 #连接池中的最小空闲连接


mybatis-plus:
  configuration:
   log-impl: org.apache.ibatis.logging.stdout.StdOutImpl