@startmindmap
* JVM内存
** 线程私有
***_ pc程序计数器
****_ 指向虚拟机字节码的位置
****_ 唯一一个不发生 OOM 的位置

***_ 虚拟机栈
****_ 生命周期与线程生命周期相同
****_ 一个线程中每个方法调用都会生成栈帧

****_ 栈帧的结构
*****_ 局部变量表
*****_ 操作数栈
*****_ 对运行时常量池的引用

****_ 异常
*****_ 线程请求的栈深度大于JVM允许的栈深度 StacKOverflowError 
*****_ 若JVM允许动态扩展, 若无法申请足够的内存 OOM

***_ 本地方法栈
****_ 异常
*****_ 线程请求的栈深度大于JVM允许的栈深度 StacKOverflowError 
*****_ 若JVM允许动态扩展, 若无法申请足够的内存 OOM


** 线程共享
***_ 方法区(元空间)
****_ 运行时常量池
***_ 堆
****_ 新生代
*****_ Eden
*****_ S1
*****_ S2

****_ 老年代
*****_ Ole
****_ 异常
*****_ OOM


** 直接内存
***_ 不受JVM GC管理



@endmindmap