spring:
  redis:
    host: 119.91.96.216
    port: 6379
    password: yy123
    database: 8
    timeout: 5000
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        max-wait: -1ms
        min-idle: 0