spring:
  redis:
    host: 119.91.96.216
    port: 6379  #Redis 端口号
    password: yy123
    lettuce:
      pool:
        max-active: 8 # 连接池最大连接数（使用负值表示没有限制）
        max-idle: 8 #连接池中的最大空闲连接
        max-wait: -1ms #连接池最大阻塞等待时间（使用负值表示没有限制）
        min-idle: 0 #连接池中的最小空闲连接

