// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: message(3).proto

package cn.tnar.msf.cm4.msg.dto;

public final class Message3 {
  private Message3() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_cmpark_message_Transmission_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_cmpark_message_Transmission_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_cmpark_message_Respond_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_cmpark_message_Respond_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\020message(3).proto\022\016cmpark.message\"\256\001\n\014T" +
      "ransmission\022\n\n\002ID\030\001 \001(\007\0226\n\004type\030\002 \001(\0162(." +
      "cmpark.message.Transmission.MessageType\022" +
      "\017\n\007message\030\003 \001(\014\"I\n\013MessageType\022\021\n\rTYPE_" +
      "NOT_USED\020\000\022\020\n\014TYPE_RESPOND\020\001\022\025\n\021TYPE_AUT" +
      "HENTICATE\020\002\"\345\001\n\007Respond\0221\n\004code\030\001 \001(\0162#." +
      "cmpark.message.Respond.RespondCode\022\017\n\007me" +
      "ssage\030\002 \001(\014\"\225\001\n\013RespondCode\022\021\n\rCODE_NOT_" +
      "USED\020\000\022\020\n\014CODE_SUCCESS\020\001\022\020\n\014CODE_FAILURE" +
      "\020\002\022\022\n\016CODE_DUPLICATE\020\003\022\021\n\rCODE_MISMATCH\020" +
      "\004\022\026\n\022CODE_NOT_SUPPORTED\020\005\022\020\n\014CODE_OFFLIN" +
      "E\020\006B\033\n\027cn.tnar.msf.cm4.msg.dtoP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_cmpark_message_Transmission_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_cmpark_message_Transmission_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_cmpark_message_Transmission_descriptor,
        new String[] { "ID", "Type", "Message", });
    internal_static_cmpark_message_Respond_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_cmpark_message_Respond_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_cmpark_message_Respond_descriptor,
        new String[] { "Code", "Message", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
