@startmindmap
* JVM GC
** gc要做的三件事
***_ 哪些内存需要回收
***_ 什么时候回收
***_ 怎么回收

** 哪些对象已死亡
***_ 引用计数法
****_ 循环引用问题
***_ 可达性分析法
****_ 通过一系列称为GC Roots 的点作为起点 向下搜索 \n当一个对象到任何 GC Roots没有引用链相连 \n说明其对象已经死亡
****_ GC Roots
*****_ VM栈中的引用
*****_ 方法区中的静态引用
*****_ JNI中的引用

** 垃圾回收算法
***_ Mark-Sweep
****_ 效率低
****_ 有碎片

***_ copy
****_ 1 eden 2-survivor

***_ Mark-compart
***_ 分代收集

** 垃圾回收器
***_ serial
***_ parNew
***_ parallel Scavenge
***_ serial old
***_ parallel old
***_ CMS - Concurrent-Mark-Sweep

** 参数
***_ Xms
***_ Xmx
***_ Xmn
***_ -XX: PrintGCDetails
***_ -XX: SurvivorRatio = 8
***_ -XX: PretenureSizeThreshold = xxx
***_ -XX: MaxTenuingThreshold
***_ -XX: HandlerPromotionFailure



@endmindmap